### ISSUE TITLE
FetchError: request to http://127.0.0.1:3030/accounts failed, reason: connect ECONNREFUSED 127.0.0.1:3030

### ISSUE THREAD

**Issue by dancomanlive** [JoinColony/hackathonStarter#5]
```
yarn start
yarn run v1.7.0
$ node src/index
{ FetchError: request to http://127.0.0.1:3030/accounts failed, reason: connect ECONNREFUSED 127.0.0.1:3030
    at ClientRequest.<anonymous> (/Users/myname/Workspace/hackathonStarter/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:160:13)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at Socket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  name: 'FetchError',
  message: 'request to http://127.0.0.1:3030/accounts failed, reason: connect ECONNREFUSED 127.0.0.1:3030',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
✨  Done in 2.81s.
```

yarn start-ganache is running

**Comment by dancomanlive** [comment]
Had to redeploy contracts on truffle to make it work

**Comment by chmanie** [comment]
Just for reference: the `http://127.0.0.1:3030/accounts` URL points to a trufflepig endpoint.
